.\" Manpage for opendlv-logic-sensation-directionofmovement
.\" Author: Ola Benderius <ola.benderius@chalmers.se>.

.TH opendlv-logic-sensation-directionofmovement 1 "26 September 2017" "0.7.4" "opendlv-logic-sensation-directionofmovement man page"

.SH NAME
opendlv-logic-sensation-directionofmovement \- This microservice returns the direction of movement based on a stream of images.



.SH SYNOPSIS
.B opendlv-logic-sensation-directionofmovement --cid=<CID>


.SH EXAMPLES
The following command joins the container conference 111:

.B opendlv-logic-sensation-directionofmovement --cid=111



.SH SEE ALSO



.SH BUGS
No known bugs.



.SH AUTHOR
Ola Benderius (ola.benderius@chalmers.se)

