language: cpp

branches:
  only:
  - "/^new$/"

cache: ccache

compiler:
- gcc

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-6

install:
- "[ $CC = gcc ] && export CC=gcc-6 || true"
- "[ $CXX = g++ ] && export CXX=g++-6 || true"

script:
- git submodule update --init --recursive && git submodule update --remote --merge && git submodule status
- for i in opendlv-device-gps-ncom opendlv-device-gps-nmea opendlv-device-gps-pos opendlv-device-lidar-hdl32e opendlv-device-lidar-vlp16; do mkdir build.$i && cd build.$i && cmake ../$i && make && make test && cd .. && rm -fr build.$i; done

notifications:
  email:
    on_success: never
    on_failure: never
  slack:
    secure: x93BCw4xMiqV7fPeNZ4Uf5S60z8xzT6BQak82yOHLjTf2TZnMqZQ+0dObgXsgMoYJtRMm5x5m57dBoA8sVv/Kj1EH3MEPJsXGmwyxlhIWA3HxgQTosiTX1MqdRs61CCESt11vxQCneHHMH7X7jN04MbNF+QufzwBuP+Ewp+ekLqMGwSfZnseZLbUyD9TG1UBtay704D37XDxB7hkglp4vD6GdxwemfGBxvcLOX02PXirvW8EJdg+OmG5seTVdi31zGMHz4ibKhZeyQE4T9D6R+OvAyQCvHXHnRpWxSYL3+iGcshSeBveKr15JyT3wE50oSSQFntQmpq7RIA64LEtnr0tfjzJgQ2vgE6Q86JHVTi4SiHgFMcrh6WVXPxDmXbV+r+V0pdL214he5cyf1OI5DJLEouJ481jLZDXku0EY/MJBzvV9Ex4cD9jnTag8GcetVT9UbJNy306cR/v+eBQG9ZdefO5HpWrSqMhFwQYPMDPABBPpjI6ss0nuxnYDCEf6SwTupaCsOb1w9glH0x2tV7EVaiBiHXVy11ihDS20koMSHcbaCclRbgDtBn/CqqISQnQfbF0G/YDAp6mMzbgELuNJMmmz41EycuTvyFhRT4Y0qvOqOjtIfkz4ob1q8YBKWNvBm5zaYMJi/+qoPytYJYRCuSjvl+CVdSOvhVbin8=
