.\" Manpage for opendlv-logic-knowledge-v2vdenm
.\" Author: Ola Benderius <ola.benderius@chalmers.se>.

.TH opendlv-logic-knowledge-v2vdenm 1 "26 September 2017" "0.7.4" "opendlv-logic-knowledge-v2vdenm man page"

.SH NAME
opendlv-logic-knowledge-v2vdenm \- This microservice converts V2V DENM messages into generic data.



.SH SYNOPSIS
.B opendlv-logic-knowledge-v2vdenm --cid=<CID>


.SH EXAMPLES
The following command joins the container conference 111:

.B opendlv-logic-knowledge-v2vdenm --cid=111



.SH SEE ALSO



.SH BUGS
No known bugs.



.SH AUTHOR
Ola Benderius (ola.benderius@chalmers.se)

