.\" Manpage for opendlv-logic-sensation-audition
.\" Author: Ola Benderius <ola.benderius@chalmers.se>.

.TH opendlv-logic-sensation-audition 1 "26 September 2017" "0.7.4" "opendlv-logic-sensation-audition man page"

.SH NAME
opendlv-logic-sensation-audition \- This microservice receives raw V2V messages.



.SH SYNOPSIS
.B opendlv-logic-sensation-audition --cid=<CID>


.SH EXAMPLES
The following command joins the container conference 111:

.B opendlv-logic-sensation-audition --cid=111



.SH SEE ALSO



.SH BUGS
No known bugs.



.SH AUTHOR
Ola Benderius (ola.benderius@chalmers.se)

