.\" Manpage for opendlv-logic-perception-detectlane
.\" Author: Ola Benderius <ola.benderius@chalmers.se>.

.TH opendlv-logic-perception-detectlane 1 "26 September 2017" "0.7.4" "opendlv-logic-perception-detectlane man page"

.SH NAME
opendlv-logic-perception-detectlane \- This microservice detects lanes from a stream of images.



.SH SYNOPSIS
.B opendlv-logic-perception-detectlane --cid=<CID>


.SH EXAMPLES
The following command joins the container conference 111:

.B opendlv-logic-perception-detectlane --cid=111



.SH SEE ALSO



.SH BUGS
No known bugs.



.SH AUTHOR
Ola Benderius (ola.benderius@chalmers.se)

