.\" Manpage for opendlv-logic-legacy-vehiclefollower
.\" Author: Ola Benderius <ola.benderius@chalmers.se>.

.TH opendlv-logic-legacy-vehiclefollower 1 "12 August 2017" "0.7.3" "opendlv-logic-legacy-vehiclefollower man page"

.SH NAME
opendlv-logic-legacy-vehiclefollower \- This microservice follows another vehicle based on GPS coordinates.



.SH SYNOPSIS
.B opendlv-logic-legacy-vehiclefollower --cid=<CID>


.SH EXAMPLES
The following command joins the container conference 111:

.B opendlv-logic-legacy-vehiclefollower --cid=111



.SH SEE ALSO



.SH BUGS
No known bugs.



.SH AUTHOR
Ola Benderius (ola.benderius@chalmers.se)

