.\" Manpage for opendlv-tool-signaladapter
.\" Author: Ola Benderius <ola.benderius@chalmers.se>.

.TH opendlv-tool-signaladapter 1 "26 September 2017" "0.7.4" "opendlv-tool-signaladapter man page"

.SH NAME
opendlv-tool-signaladapter \- This tool interfaces to the OpenDLV framework via simple UDP data streams. Suitable for Simulink/dSpace.



.SH SYNOPSIS
.B opendlv-tool-signaladapter --cid=<CID>


.SH EXAMPLES
The following command joins the container conference 111:

.B opendlv-tool-signaladapter --cid=111



.SH SEE ALSO



.SH BUGS
No known bugs.



.SH AUTHOR
Ola Benderius (ola.benderius@chalmers.se)

