.\" Manpage for opendlv-logic-sensation-echolocation
.\" Author: Ola Benderius <ola.benderius@chalmers.se>.

.TH opendlv-logic-sensation-echolocation 1 "26 September 2017" "0.7.4" "opendlv-logic-sensation-echolocation man page"

.SH NAME
opendlv-logic-sensation-echolocation \- This microservice aligns the local coordinate frame to a global one by using point cloud data.



.SH SYNOPSIS
.B opendlv-logic-sensation-echolocation --cid=<CID>


.SH EXAMPLES
The following command joins the container conference 111:

.B opendlv-logic-sensation-echolocation --cid=111



.SH SEE ALSO



.SH BUGS
No known bugs.



.SH AUTHOR
Ola Benderius (ola.benderius@chalmers.se)

