.\" Manpage for opendlv-logic-knowledge-identity
.\" Author: Ola Benderius <ola.benderius@chalmers.se>.

.TH opendlv-logic-knowledge-identity 1 "26 September 2017" "0.7.4" "opendlv-logic-knowledge-identity man page"

.SH NAME
opendlv-logic-knowledge-identity \- This microservice manages and broadcasts the internal state of the vehicle.



.SH SYNOPSIS
.B opendlv-logic-knowledge-identity --cid=<CID>


.SH EXAMPLES
The following command joins the container conference 111:

.B opendlv-logic-knowledge-identity --cid=111



.SH SEE ALSO



.SH BUGS
No known bugs.



.SH AUTHOR
Ola Benderius (ola.benderius@chalmers.se)

