if(CXXTEST_FOUND)
  file(GLOB thisproject-testsuites "${CMAKE_CURRENT_SOURCE_DIR}/testsuites/*.h")
    
  foreach(testsuite ${thisproject-testsuites})
    string(REPLACE "/" ";" testsuite-list ${testsuite})

    list(LENGTH testsuite-list len)
    math(EXPR lastItem "${len}-1")
    list(GET testsuite-list "${lastItem}" testsuite-short)

    set(CXXTEST_TESTGEN_ARGS ${CXXTEST_TESTGEN_ARGS} --world=${PROJECT_NAME}-${testsuite-short})
    CXXTEST_ADD_TEST(${testsuite-short}-TestSuite ${testsuite-short}-TestSuite.cpp ${testsuite})
    if(UNIX)
      if((("${CMAKE_SYSTEM_NAME}" STREQUAL "Linux")
          OR ("${CMAKE_SYSTEM_NAME}" STREQUAL "FreeBSD")
          OR ("${CMAKE_SYSTEM_NAME}" STREQUAL "DragonFly"))
          AND (NOT "${CMAKE_CXX_COMPILER_ID}" STREQUAL "Clang"))
        set_source_files_properties(${testsuite-short}-TestSuite.cpp PROPERTIES COMPILE_FLAGS "-Wno-effc++ -Wno-float-equal -Wno-error=suggest-attribute=noreturn")
      else()
        set_source_files_properties(${testsuite-short}-TestSuite.cpp PROPERTIES COMPILE_FLAGS "-Wno-effc++ -Wno-float-equal")
      endif()
    endif()
    if(WIN32)
      set_source_files_properties(${testsuite-short}-TestSuite.cpp PROPERTIES COMPILE_FLAGS "")
    endif()
    set_tests_properties(${testsuite-short}-TestSuite PROPERTIES TIMEOUT 3000)
    target_link_libraries(${testsuite-short}-TestSuite ${PROJECT_NAME}-static ${LIBRARIES})
  endforeach()
endif(CXXTEST_FOUND)
