.\" Manpage for opendlv-logic-action-keepobjectalignment
.\" Author: Ola Benderius <ola.benderius@chalmers.se>.

.TH opendlv-logic-action-keepobjectalignment 1 "26 September 2017" "0.7.4" "opendlv-logic-action-keepobjectalignment man page"

.SH NAME
opendlv-logic-action-keepobjectalignment \- This microservice keeps the alignment to an object.



.SH SYNOPSIS
.B opendlv-logic-action-keepobjectalignment --cid=<CID>


.SH EXAMPLES
The following command joins the container conference 111:

.B opendlv-logic-action-keepobjectalignment --cid=111



.SH SEE ALSO



.SH BUGS
No known bugs.



.SH AUTHOR
Ola Benderius (ola.benderius@chalmers.se)

