.\" Manpage for opendlv-logic-action-setopticalrotation
.\" Author: Ola Benderius <ola.benderius@chalmers.se>.

.TH opendlv-logic-action-setopticalrotation 1 "26 September 2017" "0.7.4" "opendlv-logic-action-setopticalrotation man page"

.SH NAME
opendlv-logic-action-setopticalrotation \- This microservice sets the rotation of the optical flow (flow bending).



.SH SYNOPSIS
.B opendlv-logic-action-setopticalrotation --cid=<CID>


.SH EXAMPLES
The following command joins the container conference 111:

.B opendlv-logic-action-setopticalrotation --cid=111



.SH SEE ALSO



.SH BUGS
No known bugs.



.SH AUTHOR
Ola Benderius (ola.benderius@chalmers.se)

