.\" Manpage for opendlv-logic-sensation-selflocalization
.\" Author: Ola Benderius <ola.benderius@chalmers.se>.

.TH opendlv-logic-sensation-selflocalization 1 "26 September 2017" "0.7.4" "opendlv-logic-sensation-selflocalization man page"

.SH NAME
opendlv-logic-sensation-selflocalization \- This microservice does SLAM from images



.SH SYNOPSIS
.B opendlv-logic-sensation-selflocalization --cid=<CID>


.SH EXAMPLES
The following command joins the container conference 111:

.B opendlv-logic-sensation-selflocalization --cid=111



.SH SEE ALSO



.SH BUGS
No known bugs.



.SH AUTHOR
Ola Benderius (ola.benderius@chalmers.se)

