.\" Manpage for opendlv-logic-action-keepobjectsize
.\" Author: Ola Benderius <ola.benderius@chalmers.se>.

.TH opendlv-logic-action-keepobjectsize 1 "26 September 2017" "0.7.4" "opendlv-logic-action-keepobjectsize man page"

.SH NAME
opendlv-logic-action-keepobjectsize \- This microservice keeps a fixed object size (local removal of optical flow).



.SH SYNOPSIS
.B opendlv-logic-action-keepobjectsize --cid=<CID>


.SH EXAMPLES
The following command joins the container conference 111:

.B opendlv-logic-action-keepobjectsize --cid=111



.SH SEE ALSO



.SH BUGS
No known bugs.



.SH AUTHOR
Ola Benderius (ola.benderius@chalmers.se)

