.\" Manpage for opendlv-gui-livefeed
.\" Author: Ola Benderius <ola.benderius@chalmers.se>.

.TH opendlv-gui-livefeed 1 "26 September 2017" "0.7.4" "opendlv-gui-livefeed man page"

.SH NAME
opendlv-gui-livefeed \- This microservice showes a web-based live feed of all data streamed in the conference.



.SH SYNOPSIS
.B opendlv-gui-livefeed --cid=<CID>


.SH EXAMPLES
The following command joins the container conference 111:

.B opendlv-gui-livefeed --cid=111



.SH SEE ALSO



.SH BUGS
No known bugs.



.SH AUTHOR
Ola Benderius (ola.benderius@chalmers.se)

