.\" Manpage for opendlv-gui-livefeed
.\" Author: Ola Benderius <ola.benderius@chalmers.se>.

.TH opendlv-gui-livefeed 1 "04 March 2017" "0.8.10" "opendlv-gui-livefeed man page"

.SH NAME
opendlv-gui-livefeed \- This tool interfaces with the Revere Rhino truck.



.SH SYNOPSIS
.B opendlv-gui-livefeed --cid=<CID>


.SH EXAMPLES
The following command joins the container conference 111:

.B opendlv-gui-livefeed --cid=111



.SH SEE ALSO



.SH BUGS
No known bugs.



.SH AUTHOR
Ola Benderius (ola.benderius@chalmers.se)

