.\" Manpage for opendlv-logic-sensation-geolocation
.\" Author: Ola Benderius <ola.benderius@chalmers.se>.

.TH opendlv-logic-sensation-geolocation 1 "26 September 2017" "0.7.4" "opendlv-logic-sensation-geolocation man page"

.SH NAME
opendlv-logic-sensation-geolocation \- This microservice returns the global position based on a global position estimate and internal movement data.



.SH SYNOPSIS
.B opendlv-logic-sensation-geolocation --cid=<CID>


.SH EXAMPLES
The following command joins the container conference 111:

.B opendlv-logic-sensation-geolocation --cid=111



.SH SEE ALSO



.SH BUGS
No known bugs.



.SH AUTHOR
Ola Benderius (ola.benderius@chalmers.se)

