.\" Manpage for opendlv-logic-legacy-simpledriver
.\" Author: Ola Benderius <ola.benderius@chalmers.se>.

.TH opendlv-logic-legacy-simpledriver 1 "26 September 2017" "0.7.4" "opendlv-logic-legacy-simpledriver man page"

.SH NAME
opendlv-logic-legacy-simpledriver \- This microservice follows a basic waypoint path.



.SH SYNOPSIS
.B opendlv-logic-legacy-simpledriver --cid=<CID>


.SH EXAMPLES
The following command joins the container conference 111:

.B opendlv-logic-legacy-simpledriver --cid=111



.SH SEE ALSO



.SH BUGS
No known bugs.



.SH AUTHOR
Ola Benderius (ola.benderius@chalmers.se)

